apiVersion: apps/v1
kind: Deployment
metadata:
  name: kieny-me-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kieny-me-frontend
  template:
    metadata:
      labels:
        app: kieny-me-frontend
    spec:
      containers:
      - name: kieny-me-frontend
        image: jackkieny/kieny-me-frontend:latest
        ports:
        - containerPort: 80
      - name: kieny-me-backend
        image: jackkieny/kieny-me-backend:latest
        ports:
        - containerPort: 5000

