apiVersion: apps/v1
kind: Deployment
metadata:
  name: kieny-me-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kieny-me-frontend
  template:
    metadata:
      labels:
        app: kieny-me-frontend
    spec:
      containers:
      - name: kieny-me-frontend
        image: jackkieny/kieny-me-frontend:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kieny-me-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: kieny-me-frontend
