FROM python:3.9.13-slim-buster

WORKDIR /app

ADD . /app

RUN apt-get update && apt-get install -y --no-install-recommends gcc
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["gunicorn", "-b", "0.0.0.0:5000", "flask_app.app:app"]