name: Test Pipeline

on:
  pull_request:
    branches: [ test ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create SSL certificate and key
      run: |
        echo "${{ secrets.CERT_SECRET }}" > ./frontend/kieny-me.crt
        echo "${{ secrets.KEY_SECRET }}" > ./frontend/kieny-me.key

    - name: Build React app
      run: |
        docker build -t kieny-me-frontend -f frontend/Dockerfile.frontend ./frontend

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push React app to DockerHub
      run: |
        docker tag kieny-me-frontend:latest jackkieny/kieny-me-frontend:${{ github.sha }}
        docker tag kieny-me-frontend:latest jackkieny/kieny-me-frontend:latest
        docker push jackkieny/kieny-me-frontend:${{ github.sha }}
        docker push jackkieny/kieny-me-frontend:latest
