name: Test Pipeline

on:
  pull_request:
    branches: [ test ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build React app
      run: |
        docker build -t kieny-me-frontend -f frontend/Dockerfile.frontend ./frontend
        docker build -t kieny-me-backend -f backend/Dockerfile.backend ./backend

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag and push React app to DockerHub
      run: |
        docker tag kieny-me-frontend:latest jackkieny/kieny-me-frontend:${{ github.sha }}
        docker tag kieny-me-frontend:latest jackkieny/kieny-me-frontend:latest
        docker push jackkieny/kieny-me-frontend:${{ github.sha }}
        docker push jackkieny/kieny-me-frontend:latest
    
    - name: Tag and push Flask app to DockerHub
      run: |
        docker tag kieny-me-backend:latest jackkieny/kieny-me-backend:${{ github.sha }}
        docker tag kieny-me-backend:latest jackkieny/kieny-me-backend:latest
        docker push jackkieny/kieny-me-backend:${{ github.sha }}
        docker push jackkieny/kieny-me-backend:latest
